//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripKraken.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityInfo
    {
        public int CityId { get; set; }
        public Nullable<decimal> AverageMonthlyCostPerPerson { get; set; }
        public Nullable<decimal> UtilitiesBasicCost { get; set; }
        public Nullable<decimal> ApartmentOneRoomCityCenterPrice { get; set; }
        public Nullable<decimal> MealRestourantInexpensivePrice { get; set; }
        public Nullable<decimal> DomesticBeerPrice { get; set; }
        public Nullable<decimal> Water033Price { get; set; }
        public Nullable<decimal> CoffeePrice { get; set; }
        public Nullable<decimal> TaxiStartPrice { get; set; }
        public Nullable<decimal> TaxiPerKmPrice { get; set; }
        public Nullable<decimal> AverageMonthSalary { get; set; }
    
        public virtual City City { get; set; }
    }
}
