// <auto-generated />
namespace TripKraken.DataSource.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview9-19423-04")]
    public sealed partial class _100920199 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_100920199));
        
        string IMigrationMetadata.Id
        {
            get { return "201909092251111_100920199"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
