// <auto-generated />
namespace TripKraken.DataSource.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migratio29082019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migratio29082019));
        
        string IMigrationMetadata.Id
        {
            get { return "201908282216170_Migratio29082019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
